version: "3"

services:
  oauth-server:
    image: ghcr.io/iliazeus/mastodon-tree-reader:master
    volumes: [./data:/data]
    environment:
      APPS_FILE: /data/apps.json
    networks: [external]
    restart: unless-stopped
    deploy:
      resources:
        limits: { cpus: "0.1", memory: "32M" }
    labels:
      - traefik.enable=true

      - traefik.http.routers.mastodon-tree-reader.entrypoints=web
      - traefik.http.routers.mastodon-tree-reader.rule=(Host(`ruvds.iliazeus.lol`) && PathPrefix(`/mastodon-tree-reader`))
      - traefik.http.routers.mastodon-tree-reader.middlewares=redirect-to-https@file

      - traefik.http.routers.mastodon-tree-reader-secure.entrypoints=websecure
      - traefik.http.routers.mastodon-tree-reader-secure.tls.certresolver=acme
      - traefik.http.routers.mastodon-tree-reader-secure.rule=(Host(`ruvds.iliazeus.lol`) && PathPrefix(`/mastodon-tree-reader`))

      - traefik.http.routers.mastodon-tree-reader-secure.middlewares=mastodon-tree-reader-strip-prefix,mastodon-tree-reader-cors
      - traefik.http.middlewares.mastodon-tree-reader-strip-prefix.stripprefix.prefixes=/mastodon-tree-reader
      - traefik.http.middlewares.mastodon-tree-reader-cors.headers.accesscontrolalloworiginlist=https://iliazeus.lol

networks:
  external: { external: true }
