version: "3"

services:
  backend:
    image: ghcr.io/iliazeus/punkomatic-js:master
    env_file: .env
    networks: [external]
    restart: unless-stopped

    # TODO: needs a lot of resources
    # deploy:
    #   resources:
    #     limits: { cpus: "0.25", memory: "64M" }

    labels:
      - traefik.enable=true

      - traefik.http.routers.punkomatic-js.entrypoints=web
      - traefik.http.routers.punkomatic-js.rule=(Host(`ruvds.iliazeus.lol`) && PathPrefix(`/punkomatic-js`))
      - traefik.http.routers.punkomatic-js.middlewares=redirect-to-https@file

      - traefik.http.routers.punkomatic-js-secure.entrypoints=websecure
      - traefik.http.routers.punkomatic-js-secure.tls.certresolver=acme
      - traefik.http.routers.punkomatic-js-secure.rule=(Host(`ruvds.iliazeus.lol`) && PathPrefix(`/punkomatic-js`))

      - traefik.http.routers.punkomatic-js-secure.middlewares=punkomatic-js-cors,punkomatic-js-ratelimit,punkomatic-js-strip-prefix

      - traefik.http.middlewares.punkomatic-js-strip-prefix.stripprefix.prefixes=/punkomatic-js

      - traefik.http.middlewares.punkomatic-js-ratelimit.ratelimit.period=600
      - traefik.http.middlewares.punkomatic-js-ratelimit.ratelimit.average=300
      - traefik.http.middlewares.punkomatic-js-ratelimit.ratelimit.burst=600

      - traefik.http.middlewares.punkomatic-js-cors.headers.accesscontrolalloworiginlist=*
      - traefik.http.middlewares.punkomatic-js-cors.headers.accesscontrolexposeheaders=*

networks:
  external: { external: true }
