version: "3"

services:
  bot:
    image: ghcr.io/iliazeus/mastodon-rikibooru:master
    env_file: .env
    environment:
      POST_IMMEDIATELY: ${POST_IMMEDIATELY-}
    working_dir: /data
    volumes: [./data:/data]
    networks: [external]
    restart: unless-stopped
    deploy:
      resources:
        limits: { cpus: "0.1", memory: "32M" }

networks:
  external: { external: true }
