version: "3"

services:
  traefik:
    image: traefik:v2.10.3
    networks: [external]
    ports: ["80:80", "443:443"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/dynamic:/etc/traefik/dynamic:ro
      - ./data/acme.json:/acme.json
    restart: unless-stopped

networks:
  external: { external: true }
