version: "3"

services:
  traefik:
    image: traefik:v2.10.3
    networks: [external]
    ports: ["80:80", "443:443"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/config:ro
      - ./data:/data
    restart: unless-stopped

networks:
  external: { external: true }
