log:
  level: INFO

entryPoints:
  web:
    address: ':80'
  websecure:
    address: ':443'

certificatesResolvers:
  acme:
    acme:
      email: iliazeus@proton.me
      storage: /data/acme.json
      httpChallenge:
        entryPoint: web

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /config/dynamic
    watch: true
