version: "3"

services:
  bot:
    image: ghcr.io/iliazeus/achievement-bot:master
    env_file: .env
    working_dir: /data
    volumes: [./data:/data]
    networks: [external]
    restart: unless-stopped
    deploy:
      resources:
        limits: { cpus: "0.25", memory: "64M" }

networks:
  external: { external: true }
